#!/bin/bash

find ~/.config/retroarch/states -type f -regex ".*\.png" -print0 | while read -d $'\0' thumbnail
do

    # Get the filename without extension
    save_state="${thumbnail%.png}"

    # Check if the corresponding file without extension exists
    if [ ! -e "$save_state" ]; then
        echo "Removing $thumbnail as there's no corresponding file without extension"
        rm "$thumbnail"
    fi
done

