#!/usr/bin/bash

if ! which git >> /dev/null; then
	echo "Install git on the device to configure it"
	exit 1
fi

git config --global user.name "Moffinguer"
git config --global user.email "fernandomateos.fermatgom@gmail.com"
git config --global core.editor "nvim"
git config --global diff.wsErrorHighlight "all"
git config --global filter.lfs.smudge "git-lfs smudge -- %f"
git config --global filter.lfs.process "git-lfs filter-process"
git config --global filter.lfs.required "true"
git config --global filter.lfs.clean "git-lfs clean -- %f"

